name: Netlify Production Deployment

on:
  push:
    branches:
      - main
    
jobs:
  Production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Deployed site"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
